[package]
name = "lakh"
version = "0.1.0"
authors = ["hy"]
edition = "2018"

[[bin]]
name = "lakh"
path = "src/server/main.rs"

[dependencies]
tonic= "0.3.0"
tokio = { version = "0.2", features = [ "macros", "time", "blocking" ] }
futures = "0.3.5"
rand = "0.7.3"
dashmap = "3.11.7"

[build-dependencies]
tonic-build = "0.3.0"