[package]
name = "lakh"
version = "0.1.0"
authors = ["hy"]
edition = "2018"

[[bin]]
name = "lakh"
path = "src/server/main.rs"

[dependencies]
tower = "0.3.1"
tonic= "0.3.0"
prost = "0.6"
tokio = { version = "0.2", features = [ "macros", "time", "blocking", "stream" ] }
futures = "0.3.5"
rand = "0.7.3"
dashmap = "3.11.7"
rayon = "1.3.1"
async-trait = "0.1.36"

[build-dependencies]
tonic-build = {version = "0.3.0", features = ["prost"]}